/**
 * Build step. Three jobs, all of which need to happen after the HTML is
 * final and none of which can be done in the browser.
 *
 *   1. Stamp the real site address into og:image and canonical. Social
 *      scrapers do not resolve relative paths and do not run JavaScript.
 *   2. Generate _headers, including a Content-Security-Policy whose script
 *      and style hashes are computed from the file that just shipped. A
 *      hand-written hash goes stale the first time anyone edits the page;
 *      a computed one cannot.
 *   3. Generate robots.txt and sitemap.xml, which need the address too.
 *
 * Netlify sets `URL` on every build, so this needs no configuration.
 * `SITE_URL` overrides it. With neither, steps 1 and 3 are skipped and the
 * placeholders are left intact - running this locally must not eat them.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC = join(ROOT, 'public');
const INDEX = join(PUBLIC, 'index.html');

const siteUrl = (process.env.SITE_URL || process.env.URL || process.env.DEPLOY_PRIME_URL || '')
  .replace(/\/+$/, '');

// --- 1. stamp -----------------------------------------------------------------
let html = await readFile(INDEX, 'utf8');

if (siteUrl) {
  html = html.replaceAll('__SITE_URL__', siteUrl);
  await writeFile(INDEX, html);
  console.log(`build: stamped ${siteUrl}`);
} else {
  console.warn('build: no SITE_URL / URL set - leaving placeholders, skipping robots/sitemap');
}

// --- 2. CSP over what actually shipped ----------------------------------------
const sha256 = (text) => `'sha256-${createHash('sha256').update(text, 'utf8').digest('base64')}'`;

const collect = (source, tag) =>
  [...source.matchAll(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)</${tag}>`, 'g'))]
    .map((m) => m[1])
    .filter((body) => body.trim().length);

const scriptHashes = collect(html, 'script').map(sha256);
const styleHashes = collect(html, 'style').map(sha256);

if (!scriptHashes.length || !styleHashes.length) {
  console.error('build: found no inline script or style to hash - refusing to write a CSP that would break the page');
  process.exit(1);
}

const csp = [
  "default-src 'none'",
  `script-src ${scriptHashes.join(' ')}`,
  `style-src ${styleHashes.join(' ')}`,
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",       // the audit endpoint, same origin
  "form-action 'none'",       // every form is handled in JavaScript
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'"
].join('; ');

const headers = `# Generated by scripts/build.js - do not edit by hand.
# The CSP hashes are computed from public/index.html at build time, so they
# cannot drift out of date the way a hand-written hash does.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains

/og.png
  Cache-Control: public, max-age=86400
/favicon.svg
  Cache-Control: public, max-age=86400
/apple-touch-icon.png
  Cache-Control: public, max-age=86400
`;

await writeFile(join(PUBLIC, '_headers'), headers);
console.log(`build: wrote _headers (${scriptHashes.length} script, ${styleHashes.length} style hash)`);

// --- 3. robots + sitemap ------------------------------------------------------
if (siteUrl) {
  await writeFile(join(PUBLIC, 'robots.txt'),
    `User-agent: *\nAllow: /\n\n# The audit endpoint is not content.\nDisallow: /.netlify/\n\nSitemap: ${siteUrl}/sitemap.xml\n`);

  const today = new Date().toISOString().slice(0, 10);
  await writeFile(join(PUBLIC, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `  <url>\n    <loc>${siteUrl}/</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>monthly</changefreq>\n  </url>\n` +
    `</urlset>\n`);

  console.log('build: wrote robots.txt and sitemap.xml');
}
